[build]
  base = "Interfaz"
  command = "npm run build"
  publish = "dist"

# Proxy: todo lo que empiece con /api/ va a tu backend
[[redirects]]
  from = "/api/*"
  to = "https://TU-BACKEND.vercel.app/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Opcional) Headers CORS sobre el proxy (no functions)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
